package com.blogzhou.entity;

// Generated 2014-9-24 15:31:13 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PubOrganType generated by hbm2java
 */
public class PubOrganType implements java.io.Serializable {

	private String organType;
	private String typeName;
	private String parentType;
	private char inUse;
	private Date ctime;
	private Set pubOrgans = new HashSet(0);

	public PubOrganType() {
	}

	public PubOrganType(String organType, String typeName, String parentType,
			char inUse, Date ctime) {
		this.organType = organType;
		this.typeName = typeName;
		this.parentType = parentType;
		this.inUse = inUse;
		this.ctime = ctime;
	}

	public PubOrganType(String organType, String typeName, String parentType,
			char inUse, Date ctime, Set pubOrgans) {
		this.organType = organType;
		this.typeName = typeName;
		this.parentType = parentType;
		this.inUse = inUse;
		this.ctime = ctime;
		this.pubOrgans = pubOrgans;
	}

	public String getOrganType() {
		return this.organType;
	}

	public void setOrganType(String organType) {
		this.organType = organType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getParentType() {
		return this.parentType;
	}

	public void setParentType(String parentType) {
		this.parentType = parentType;
	}

	public char getInUse() {
		return this.inUse;
	}

	public void setInUse(char inUse) {
		this.inUse = inUse;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Set getPubOrgans() {
		return this.pubOrgans;
	}

	public void setPubOrgans(Set pubOrgans) {
		this.pubOrgans = pubOrgans;
	}

}
