package com.blogzhou.entity;

// Generated 2014-9-24 15:31:13 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PubStruType generated by hbm2java
 */
public class PubStruType implements java.io.Serializable {

	private String struType;
	private String typeName;
	private String rootId;
	private char isDefault;
	private String note;
	private char inUse;
	private Date ctime;
	private Set pubStrus = new HashSet(0);
	private Set pubStruExts = new HashSet(0);

	public PubStruType() {
	}

	public PubStruType(String struType, String typeName, String rootId,
			char isDefault, char inUse, Date ctime) {
		this.struType = struType;
		this.typeName = typeName;
		this.rootId = rootId;
		this.isDefault = isDefault;
		this.inUse = inUse;
		this.ctime = ctime;
	}

	public PubStruType(String struType, String typeName, String rootId,
			char isDefault, String note, char inUse, Date ctime, Set pubStrus,
			Set pubStruExts) {
		this.struType = struType;
		this.typeName = typeName;
		this.rootId = rootId;
		this.isDefault = isDefault;
		this.note = note;
		this.inUse = inUse;
		this.ctime = ctime;
		this.pubStrus = pubStrus;
		this.pubStruExts = pubStruExts;
	}

	public String getStruType() {
		return this.struType;
	}

	public void setStruType(String struType) {
		this.struType = struType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getRootId() {
		return this.rootId;
	}

	public void setRootId(String rootId) {
		this.rootId = rootId;
	}

	public char getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(char isDefault) {
		this.isDefault = isDefault;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public char getInUse() {
		return this.inUse;
	}

	public void setInUse(char inUse) {
		this.inUse = inUse;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Set getPubStrus() {
		return this.pubStrus;
	}

	public void setPubStrus(Set pubStrus) {
		this.pubStrus = pubStrus;
	}

	public Set getPubStruExts() {
		return this.pubStruExts;
	}

	public void setPubStruExts(Set pubStruExts) {
		this.pubStruExts = pubStruExts;
	}

}
