package com.blogzhou.entity;

// Generated 2014-9-24 15:31:13 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PubStru generated by hbm2java
 */
public class PubStru implements java.io.Serializable {

	private String struId;
	private String pubStruType;
	private String organId;
	private String parentId;
	private int struLevel;
	private String struPath;
	private int struOrder;
	private char isLeaf;
	private char inUse;
	private String positionCode;
	private Date ctime;
	private String struName;
	private String struCode;

	public PubStru() {
	}

	public PubStru(String struId, String pubStruType, int struLevel,
			String struPath, int struOrder, char isLeaf, char inUse, Date ctime) {
		this.struId = struId;
		this.pubStruType = pubStruType;
		this.struLevel = struLevel;
		this.struPath = struPath;
		this.struOrder = struOrder;
		this.isLeaf = isLeaf;
		this.inUse = inUse;
		this.ctime = ctime;
	}


	public String getStruId() {
		return this.struId;
	}

	public void setStruId(String struId) {
		this.struId = struId;
	}

	
	
	public String getPubStruType() {
		return pubStruType;
	}

	public void setPubStruType(String pubStruType) {
		this.pubStruType = pubStruType;
	}

	public String getOrganId() {
		return this.organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public int getStruLevel() {
		return this.struLevel;
	}

	public void setStruLevel(int struLevel) {
		this.struLevel = struLevel;
	}

	public String getStruPath() {
		return this.struPath;
	}

	public void setStruPath(String struPath) {
		this.struPath = struPath;
	}

	public int getStruOrder() {
		return this.struOrder;
	}

	public void setStruOrder(int struOrder) {
		this.struOrder = struOrder;
	}

	public char getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(char isLeaf) {
		this.isLeaf = isLeaf;
	}

	public char getInUse() {
		return this.inUse;
	}

	public void setInUse(char inUse) {
		this.inUse = inUse;
	}

	public String getPositionCode() {
		return this.positionCode;
	}

	public void setPositionCode(String positionCode) {
		this.positionCode = positionCode;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public String getStruName() {
		return this.struName;
	}

	public void setStruName(String struName) {
		this.struName = struName;
	}

	public String getStruCode() {
		return this.struCode;
	}

	public void setStruCode(String struCode) {
		this.struCode = struCode;
	}

}
