package com.blogzhou.entity;

// Generated 2014-9-24 15:31:13 by Hibernate Tools 4.0.0

/**
 * PubStruExt generated by hbm2java
 */
public class PubStruExt implements java.io.Serializable {

	private String id;
	private String pubStru;
	private String pubStruType;
	private String type;
	private String srcId;
	private String targetId;

	public PubStruExt() {
	}



	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSrcId() {
		return this.srcId;
	}

	public void setSrcId(String srcId) {
		this.srcId = srcId;
	}

	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}



	public String getPubStru() {
		return pubStru;
	}



	public void setPubStru(String pubStru) {
		this.pubStru = pubStru;
	}



	public String getPubStruType() {
		return pubStruType;
	}



	public void setPubStruType(String pubStruType) {
		this.pubStruType = pubStruType;
	}
	
}
