package com.blogzhou.entity;

// Generated 2014-9-24 15:31:13 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PubOrgan generated by hbm2java
 */
public class PubUsers implements java.io.Serializable {

	private String userid;
	private String userTypeCode;
	private String userName;
	private String password;
	private char accountStatus;
	private char isSys;
	private String createTime;
	private String lockTime;
	private String expiredTime;
	private String pwdUptTime;
	private String pwdTime;
	private Integer idNum;

	private String corporationid;
	
	private String departmenid;
	
	private String struId;
	
	public PubUsers() {
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUserTypeCode() {
		return userTypeCode;
	}

	public void setUserTypeCode(String userTypeCode) {
		this.userTypeCode = userTypeCode;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public char getAccountStatus() {
		return accountStatus;
	}

	public void setAccountStatus(char accountStatus) {
		this.accountStatus = accountStatus;
	}

	public char getIsSys() {
		return isSys;
	}

	public void setIsSys(char isSys) {
		this.isSys = isSys;
	}

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getLockTime() {
		return lockTime;
	}

	public void setLockTime(String lockTime) {
		this.lockTime = lockTime;
	}

	public String getExpiredTime() {
		return expiredTime;
	}

	public void setExpiredTime(String expiredTime) {
		this.expiredTime = expiredTime;
	}

	public String getPwdUptTime() {
		return pwdUptTime;
	}

	public void setPwdUptTime(String pwdUptTime) {
		this.pwdUptTime = pwdUptTime;
	}

	public String getPwdTime() {
		return pwdTime;
	}

	public void setPwdTime(String pwdTime) {
		this.pwdTime = pwdTime;
	}

	public Integer getIdNum() {
		return idNum;
	}

	public void setIdNum(Integer idNum) {
		this.idNum = idNum;
	}

	public String getCorporationid() {
		return corporationid;
	}

	public void setCorporationid(String corporationid) {
		this.corporationid = corporationid;
	}

	public String getDepartmenid() {
		return departmenid;
	}

	public void setDepartmenid(String departmenid) {
		this.departmenid = departmenid;
	}

	public String getStruId() {
		return struId;
	}

	public void setStruId(String struId) {
		this.struId = struId;
	}					
	
}
